/** API 错误码枚举 —— 所有 API 路由返回的错误码的唯一定义 */
export enum ErrorCode {
  // 通用
  UNKNOWN = "UNKNOWN",
  INVALID_JSON = "INVALID_JSON",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  AI_UNAVAILABLE = "AI_UNAVAILABLE",

  // 记忆
  MEMORY_NOT_FOUND = "MEMORY_NOT_FOUND",
  MEMORY_CREATE_FAILED = "MEMORY_CREATE_FAILED",
  MEMORY_UPDATE_FAILED = "MEMORY_UPDATE_FAILED",
  MEMORY_DELETE_FAILED = "MEMORY_DELETE_FAILED",
  MEMORY_QUERY_FAILED = "MEMORY_QUERY_FAILED",
  MEMORY_VECTOR_FAILED = "MEMORY_VECTOR_FAILED",

  // 摄取
  INGEST_FAILED = "INGEST_FAILED",

  // 审计
  AUDIT_CONFLICT = "AUDIT_CONFLICT",
  AUDIT_QUEUE_FULL = "AUDIT_QUEUE_FULL",
}

/** 错误码对应的 HTTP 状态码映射 */
export const ERROR_HTTP_STATUS: Record<string, number> = {
  [ErrorCode.UNKNOWN]: 500,
  [ErrorCode.INVALID_JSON]: 400,
  [ErrorCode.VALIDATION_FAILED]: 400,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.AI_UNAVAILABLE]: 503,
  [ErrorCode.MEMORY_NOT_FOUND]: 404,
  [ErrorCode.MEMORY_CREATE_FAILED]: 500,
  [ErrorCode.MEMORY_UPDATE_FAILED]: 500,
  [ErrorCode.MEMORY_DELETE_FAILED]: 500,
  [ErrorCode.MEMORY_QUERY_FAILED]: 500,
  [ErrorCode.MEMORY_VECTOR_FAILED]: 500,
  [ErrorCode.INGEST_FAILED]: 500,
  [ErrorCode.AUDIT_CONFLICT]: 409,
  [ErrorCode.AUDIT_QUEUE_FULL]: 429,
};
